--CONSULT US-PRIYA
CREATE TABLE CONSULT_US
(CITY VARCHAR(30) NOT NULL,
CUSNAME VARCHAR(10) NOT NULL,
MOBNO NUMERIC(10) NOT NULL,
EMAILID VARCHAR(30) NOT NULL,
PACKAGE_WEIGHT NUMERIC(6) NOT NULL,
VEHICAL_TYPE VARCHAR(30) NOT NULL,
FROM_ADDRESS VARCHAR(50) NOT NULL,
TO_ADDRESS VARCHAR(50) NOT NULL,
STATUS_ID VARCHAR(10),
CreatedBy VARCHAR(20) NOT NULL,
CreateDate DATETIME NOT NULL, 
ModifiedBy VARCHAR(20) NOT NULL, 
ModifiedDate DATETIME NOT NULL, 
RecordStatus BIT NOT NULL, 
RowGUID VARCHAR(MAX));
SELECT * FROM CONSULT_US
go
--INSERT
CREATE PROCEDURE CONSULT_US_PROC

@CITY VARCHAR(30),
@CUSNAME VARCHAR(10),
@MOBNO NUMERIC(10),
@EMAILID VARCHAR(30),
@PACKAGE_WEIGHT NUMERIC(6),
@VEHICAL_TYPE VARCHAR(30), 
@FROM_ADDRESS VARCHAR(50),
@TO_ADDRESS VARCHAR(50),
@STATUS_ID VARCHAR(10)

AS
begin

INSERT INTO CONSULT_US VALUES(@CITY,@CUSNAME,@MOBNO,@EMAILID,@PACKAGE_WEIGHT,@VEHICAL_TYPE,@FROM_ADDRESS,@TO_ADDRESS,@STATUS_ID,CURRENT_USER, CURRENT_TIMESTAMP ,CURRENT_USER, CURRENT_TIMESTAMP, 1, NEWID())

end

EXEC CONSULT_US_PROC 'TRICHY','SELVI',8840425644,'selvi12@gmail.com',500,'TATA ACE','abcplace','xyzplace','0'
SELECT * FROM CONSULT_US
go

-- PROCEDURE FOR UPDATE
CREATE PROCEDURE [dbo].[STATUS_ID_PROC]

@STATUS_ID VARCHAR(10)
AS
BEGIN
UPDATE CONSULT_US SET STATUS_ID = @STATUS_ID, ModifiedBy = CURRENT_USER, ModifiedDate = CURRENT_TIMESTAMP
END
EXEC STATUS_ID_PROC 1
GO
SELECT * FROM CONSULT_US
